if(NOT ONNX_SOURCE_DIR)
    message(FATAL_ERROR "ONNX_SOURCE_DIR required")
endif()
set(ORT_MUTEX_H "${ONNX_SOURCE_DIR}/include/onnxruntime/core/platform/ort_mutex.h")
if(EXISTS "${ORT_MUTEX_H}")
    file(READ "${ORT_MUTEX_H}" CONTENT)
    if(NOT CONTENT MATCHES "#include <chrono>")
        string(REPLACE "#include <mutex>" "#include <chrono>\n#include <mutex>" CONTENT "${CONTENT}")
        file(WRITE "${ORT_MUTEX_H}" "${CONTENT}")
        message(STATUS "Patched ort_mutex.h: added #include <chrono>")
    endif()
endif()
