if(NOT ONNX_SOURCE_DIR)
    message(FATAL_ERROR "ONNX_SOURCE_DIR required")
endif()
set(EIGEN_CMAKE_FILE "${ONNX_SOURCE_DIR}/cmake/external/eigen.cmake")
if(EXISTS "${EIGEN_CMAKE_FILE}")
    file(READ "${EIGEN_CMAKE_FILE}" EIGEN_CMAKE)
    string(REGEX REPLACE "\n[ \t]*URL_HASH SHA1=\\$\\{DEP_SHA1_eigen\\}[ \t]*\n" "\n" EIGEN_CMAKE "${EIGEN_CMAKE}")
    file(WRITE "${EIGEN_CMAKE_FILE}" "${EIGEN_CMAKE}")
    message(STATUS "Patched Eigen SHA1 check (GitLab archive changed)")
endif()
